// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// NumberCategorization is an autogenerated mock type for the NumberCategorization type
type NumberCategorization struct {
	mock.Mock
}

// Resource provides a mock function with given fields: c
func (_m *NumberCategorization) Resource(c *echo.Group) {
	_m.Called(c)
}

type mockConstructorTestingTNewNumberCategorization interface {
	mock.TestingT
	Cleanup(func())
}

// NewNumberCategorization creates a new instance of NumberCategorization. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNumberCategorization(t mockConstructorTestingTNewNumberCategorization) *NumberCategorization {
	mock := &NumberCategorization{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
